### ISSUE TITLE
Uncaught TypeError: this.element.querySelector is not a function

### ISSUE THREAD

**Issue by hollmanenciso** [mschuchard/linter-terraform-syntax#5]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 ia32
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [linter-terraform-syntax](https://github.com/mschuchard/linter-terraform-syntax) package 1.1.2

### Stack Trace

Uncaught TypeError: this.element.querySelector is not a function

```
At C:\Users\henciso\.atom\packages\linter-terraform-syntax\node_modules\atom-package-deps\lib\view.js:41

TypeError: this.element.querySelector is not a function
    at View.advance (/packages/linter-terraform-syntax/node_modules/atom-package-deps/lib/view.js:41:36)
    at /packages/linter-terraform-syntax/node_modules/atom-package-deps/lib/main.js:53:16
    at stdout (/packages/linter-terraform-syntax/node_modules/atom-package-deps/lib/helpers.js:24:11)
    at Socket.<anonymous> (~/AppData/Local/atom/app-1.17.0/resources/app/src/buffered-process.js:212:1)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
```

### Commands

```
     -2:10.2.0 core:move-right (input.hidden-input)
     -2:09.8.0 core:move-left (input.hidden-input)
  3x -1:48.7.0 core:move-down (input.hidden-input)
  2x -1:48 core:move-up (input.hidden-input)
     -1:47.2.0 core:move-right (input.hidden-input)
  2x -1:46.9.0 core:move-up (input.hidden-input)
  3x -1:46.1.0 core:move-down (input.hidden-input)
     -1:45.2.0 core:move-up (input.hidden-input)
 39x -1:44.9.0 core:move-right (input.hidden-input)
 11x -1:41.4.0 core:move-down (input.hidden-input)
  2x -1:38.7.0 core:backspace (input.hidden-input)
     -1:35.7.0 core:save (input.hidden-input)
 10x -1:20.6.0 core:move-up (input.hidden-input)
 26x -1:17.9.0 core:move-right (input.hidden-input)
  3x -1:15.2.0 core:move-down (input.hidden-input)
     -1:12.4.0 core:move-up (input.hidden-input)
```

### Non-Core Packages

```
docker 0.7.0 
git-control 0.9.0 
language-docker 1.1.7 
language-terraform 0.8.1 
linter 2.1.4 
linter-terraform-syntax 1.1.2 
markdown-preview-plus 2.4.9 
markdown-writer 2.6.4 
```

**Comment by mschuchard** [comment]
Fixed in 2089b5eda80ca27e02cc47f7fc9078bfb834c27c.
