### ISSUE TITLE
Failed to load the linter-terraform-syntax package

### ISSUE THREAD

**Issue by avineshwar** [mschuchard/linter-terraform-syntax#9]
1. Install Atom
2. Install package
3. Install other packages if you feel like

Got that error right after it, out of the blue.

**Atom**: 1.24.1 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [linter-terraform-syntax](https://github.com/mschuchard/linter-terraform-syntax) package 1.2.2

### Stack Trace

Failed to load the linter-terraform-syntax package

```
At EPERM: operation not permitted, open 'C:\Users\avine\.atom\packages\linter-terraform-syntax\lib\main.js'

Error: EPERM: operation not permitted, open 'C:\Users\avine\.atom\packages\linter-terraform-syntax\lib\main.js'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Proxy.fs.readFileSync (fs.js:468:33)
    at Proxy.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at compileFileAtPath (~/AppData/Local/atom/app-1.24.1/resources/app/src/compile-cache.js:89:29)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.24.1/resources/app/src/compile-cache.js:238:26)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.24.1/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.24.1/resources/app/src/package.js:782:33)
    at measure (~/AppData/Local/atom/app-1.24.1/resources/app/src/package.js:143:22)
    at Package.measure (~/AppData/Local/atom/app-1.24.1/resources/app/src/package.js:88:25)
    at Package.load (~/AppData/Local/atom/app-1.24.1/resources/app/src/package.js:129:16)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.24.1/resources/app/src/package-manager.js:618:16)
    at PackageManager.loadPackage (~/AppData/Local/atom/app-1.24.1/resources/app/src/package-manager.js:551:25)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.24.1/resources/app/src/package-manager.js:689:23)
    at ~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (~/AppData/Local/atom/app-1.24.1/resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.24.1/resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
 15x -5:07.0 core:move-down (div.panels-item)
 25x -5:05.9.0 core:move-up (div.panels-item)
     -4:59.6.0 core:backspace (input.hidden-input)
     -4:59.1.0 core:confirm (input.hidden-input)
     -4:50.6.0 core:select-all (input.hidden-input)
     -4:47.9.0 core:confirm (input.hidden-input)
     -4:30.7.0 core:backspace (input.hidden-input)
     -4:29.8.0 core:confirm (input.hidden-input)
     -4:19.7.0 core:select-all (input.hidden-input)
  2x -4:17.3.0 core:confirm (input.hidden-input)
  3x -1:51.4.0 editor:select-to-beginning-of-word (input.hidden-input)
     -1:49.1.0 core:confirm (input.hidden-input)
     -1:32.1.0 core:close (div.panels-item)
     -1:29.4.0 pane:reopen-closed-item (input.hidden-input)
     -1:27.6.0 core:confirm (input.hidden-input)
 10x -0:45.9.0 core:move-down (div.panels-item)
```

### Non-Core Packages

```
language-terraform 0.8.1 
linter-terraform-syntax 1.2.2 
teletype 0.10.0 
```

**Comment by mschuchard** [comment]
I have no idea how Windows permissions work and why it might be blocking the package loading. I know people have used this on Windows, but I do not know anything beyond that.

This might be better posted on a Stack Exchange site; otherwise, I could ask someone I know who has a Windows laptop to try installing this in Atom (I think he uses Sublime normally).

**Comment by mschuchard** [comment]
Checking on how this is going in v1.2.5.
